### ISSUE TITLE
don't working in node 14

### ISSUE THREAD

**Issue by Debbl** [antfu/ni#197]
### Describe the bug

I get an error, because the node 14 doesn't have built-in `node:timers/promises`

related issues https://github.com/antfu/ni/issues/192

```bash
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
    at new NodeError (internal/errors.js:322:7)
    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
    at new ModuleJob (internal/modules/esm/module_job.js:63:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
    at async Promise.all (index 11)
    at async link (internal/modules/esm/module_job.js:83:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
```

### Reproduction
```bash
sudo npm i n -g
```
```bash
sudo n 14
```
```bash
ni
```
the error
```bash
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
    at new NodeError (internal/errors.js:322:7)
    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
    at new ModuleJob (internal/modules/esm/module_job.js:63:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
    at async Promise.all (index 11)
    at async link (internal/modules/esm/module_job.js:83:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
```

It seems to be an `extra` problem, it works if I change `execa` to `7.1.1`.
```diff
- "execa": "^8.0.1",
+ "execa": "^7.1.1",
```

### Reproduction

above

### System Info

```Shell
System:
    OS: macOS 14.2
    CPU: (8) x64 Apple M1 Pro
    Memory: 43.56 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 6.14.17 - /usr/local/bin/npm
    bun: 1.0.14 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I don't mind downgrading execa, but for future-proof I'd also suggest you to upgrade your node.

PR Welcome :)

**Comment by sxzz** [comment]
We're currently using `tinyexec`, which may support Node 14. If it does not, please downgrade and pin `@antfu/ni` to a version that supports Node 14, as Node 14 has been end-of-life for quite some time.
